spring:
  application:
    name: execute

  profiles:
    active: local # default
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - application-rds-local.yml
      - application-hc-local.yml

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.web.servlet: DEBUG

    root: info
    com.drinkhere: debug
