spring:
  application:
    name: monitoring

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      cors:
        allowed-origins: "*"
        allowed-methods: GET
  prometheus:
    metrics:
      export:
        enabled: true